version: '3.9' 
# Specifies the Docker Compose file format version. 3.9 is the latest stable version for most use cases.

services:
  app:
    build: .
    ports:
      - "5501:5501"
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/code:/tmp/code  # <-- Mount code directory for job files
    env_file:
      - .env
    restart: unless-stopped
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped